### PR TITLE
Typos fix

### PR DESCRIPTION
**Pull request by Atcold**

### CODE REVIEW

**Comment by jchook** [comment]
I was about to make the same PR!

**Comment by Atcold** [comment]
Let's have @colah merge it, then.

**Comment by colah** [comment]
D'oh, thanks for drawing my attention to this!

(That said, my workflow is kind of broken. It's probably better to make pull requests to the colah.github.io repo.)

**Comment by Atcold** [comment]
@jchook, feel free to submit the PR to the other repo, perhaps referencing this PR.

**Pull request merged**
