### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by jhorowitz**

### CODE REVIEW

**Comment by jhorowitz** [comment]
Thank you for the great article!

**Comment by colah** [comment]
Thanks for the fix! :)

(Because of technical debt and decay in my build process, this may not propagate. I appreciate the PR regardless. If it's important to you to make sure it does propagate, please make a PR to the colah/colah.github.io repo)

**Comment by jhorowitz** [comment]
Ah, I didn't realize. I'll make a PR to the other repo.

**Comment by colah** [comment]
It's entirely my fault for letting stuff break. Thanks for the second PR.

**Comment by jhorowitz** [comment]
Your blog posts have been incredibly helpful in my quest to learn ML. I'm happy to help.

**Pull request merged**
